version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  server-app:
    build: ./
    # container_name: server_app_container
    restart: always
    ports:
      - 3000:3000
    network_mode: host
    environment:
      MONGODB_ADMIN_USERNAME: root
      MONGODB_ADMIN_PASSWORD: example
    depends_on:
      - mongo